<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p id="demo"></p>
    <p>Notice that the <b>statement</b> inside the <b>finally</b> statement was executed even though an <b>exception</b> was <b>thrown</b>.</p>
    <p>Try to remove the <b>throw</b> statement, and see what happens. </p>
    <script>
        try{
           throw"An error occured, please fix it!"; 
        }
        catch(err){
            document.getElementById("demo").innerHTML = err;
        }
        finally{
            alert("Hello Programmer");
        }
    </script>
</body>
</html>